/*
 * generated by Xtext
 */
package de.grammarcraft.flow.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.grammarcraft.flow.ui.internal.FlowActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FlowExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FlowActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FlowActivator.getInstance().getInjector(FlowActivator.DE_GRAMMARCRAFT_FLOW_FLOW);
	}
	
}
