/*
 * generated by Xtext
 */
package de.grammarcraft.flow.ui.contentassist

import de.grammarcraft.flow.ui.contentassist.AbstractFlowProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FlowProposalProvider extends AbstractFlowProposalProvider {
}
