/*
* generated by Xtext
*/
package de.grammarcraft.flow;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FlowUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.grammarcraft.flow.ui.internal.FlowActivator.getInstance().getInjector("de.grammarcraft.flow.Flow");
	}
	
}
